apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 1
  #selector:
    #app: nginx
    #env: production
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        version: 1.11.10
        env: production
    spec:
      containers:
      - name: nginx
        image: nginx:1.11.10
        ports:
        - containerPort: 80
