apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  #selector:
    #matchLabels:
      #app: nginx
    #matchExpressions:
      #- {key: env, operator: In, values: [staging]}
  template:
    metadata:
      labels:
        app: nginx
        env: staging
        version: 1.11.10
    spec:
      containers:
      - name: nginx
        image: nginx:1.11.10
        ports:
        - containerPort: 80
